package GUI;
import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableColumn;
import java.util.Vector;

public class CustomerRetrievalForm extends javax.swing.JDialog {


    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration   
	
    /**
     * Creates new form CustomerReterivalForm
     */
    
    public CustomerRetrievalForm(Vector searchlist) {
    	setTitle("Customer Data");
    	setModal(true);
    	
        initComponents(searchlist);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(Vector searchList) {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();


        Vector colNames = new Vector();
        
        String[] strColNames = new String []{ "cid-1", "Fname", "Lname", "Address", "phonenum", "phone", "emailid", "DOB", "flag"};
        
        String str;
        for(int i = 0; i < strColNames.length; i++) {
            colNames.add(strColNames[i]);
        }
        
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel( searchList, colNames)
/*
            new Object [][] {
                {1, 2, 3, 4, 5, null, null, null, null},
              },
            new String [] {
                "cid", "Fname", "Lname", "Address", "phonenum", "phone", "emailid", "DOB", "flag"
            }
*/
        );
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    	System.out.println(" in customer retival form - Start");
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerRetrievalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerRetrievalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerRetrievalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerRetrievalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new CustomerRetrievalForm().setVisible(true);
            }
        });
        // "cid", "Fname", "Lname", "Address", "phonenum", "phone", "emailid", "DOB", "flag"+
/*        
        String [] columnNames = {"cid", "Fname", "Lname", "Address", "phonenum", "phone", "emailid", "DOB", "flag"};
        dataModel = new DefaultTableModel();
        String[] row = { "1",  "Amit", "C", "Addr 1", "Phone num1", "Phone -1", "emailid@abc.com", "11/11/2011", "d"};
        dataModel.setColumnIdentifiers(columnNames);
		dataModel.addRow(row);

        */

        // CustomerRetrievalForm custRetForm = new CustomerRetrievalForm();
        
        //custRetForm.jTable1.getModel().addRow(row);
       // javax.swing.table.DefaultTableModel
       // System.out.println(" in customer retival form - end");
    }
}
