package GUI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import java.awt.Dimension;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author AMIT
 */

public class Demography extends javax.swing.JDialog {
    private static CafeBill _cb;
    public Demography(CafeBill cb){
        _cb = cb;
    }
    private static Connection connect = null;
    private static PreparedStatement preparedStatement = null;
    private static ResultSet resultSet = null;
    /**
     * Creates new form demography
     */
    public Demography() {
        setModal(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "deprecation" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        lblno_of_guests = new javax.swing.JLabel();
        lblno_of_guests.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentMoved(ComponentEvent arg0) {
            }
        });
        lblMale = new javax.swing.JLabel();
        lblMale.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentMoved(ComponentEvent arg0) {
            }
        });
        lblFemale = new javax.swing.JLabel();
        lblFemale.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentMoved(ComponentEvent arg0) {
            }
        });
        lblKids = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox1.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentMoved(ComponentEvent arg0) {
            }
        });
        btnSubmit = new javax.swing.JButton();
        btnSubmit.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentMoved(ComponentEvent arg0) {
            }
        });
        btnCancel = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();// JComboBox 1,4,5,6,7,8 are of male TODO update there ProperName
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox4.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentMoved(ComponentEvent arg0) {
            }
        });
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox(); // JComboBox 2,9,10,11,12,13 are of female TODO update there ProperName
        jComboBox9 = new javax.swing.JComboBox();
        jComboBox10 = new javax.swing.JComboBox();
        jComboBox11 = new javax.swing.JComboBox();
        jComboBox12 = new javax.swing.JComboBox();
        jComboBox13 = new javax.swing.JComboBox();
        jComboBox14 = new javax.swing.JComboBox();//JComboBox3,15,15,16,17,18 are of Kids TODO update there ProperName
        jComboBox15 = new javax.swing.JComboBox();
        jComboBox16 = new javax.swing.JComboBox();
        jComboBox17 = new javax.swing.JComboBox();
        jComboBox18 = new javax.swing.JComboBox();



        jLabel1 = new javax.swing.JLabel();
        btnclear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(400, 100));
        setName("Demography"); // NOI18N

        lblno_of_guests.setText("Number Of Guest");

        lblMale.setText("Male");

        lblFemale.setText("Female");

        lblKids.setText("Kids");

        try {
            Class.forName("com.mysql.jdbc.Driver");
            // Setup the connection with the DB
            connect = DriverManager.getConnection(CafeBill.hmsDbUrl);
        }
        catch (ClassNotFoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        //String ageGroup [] = new String[] { "None" ,"ageCategory" };
        try {
            String query="SELECT * FROM male_age_group";
            preparedStatement=connect.prepareStatement(query);
            ResultSet rs = preparedStatement.executeQuery();
            jComboBox1.addItem("None");
            jComboBox4.addItem("None");
            jComboBox5.addItem("None");
            jComboBox6.addItem("None");
            jComboBox7.addItem("None");
            jComboBox8.addItem("None");

            for(int i = 1; rs.next(); i ++)
            {
                int id = rs.getInt("id");
                int age_group_start = rs.getInt("age_group_start");
                int age_group_end = rs.getInt("age_group_end");
                int start = age_group_start; // rs.get(row, col1) --> start of age group
                int end = age_group_end;  // rs.get(row, col2) --> end of age group

                String ageCategorymale = (start + " - " + end);
                System.out.println( "values from male_age_group table " + ageCategorymale );
                jComboBox1.addItem(ageCategorymale);
                jComboBox4.addItem(ageCategorymale);
                jComboBox5.addItem(ageCategorymale);
                jComboBox6.addItem(ageCategorymale);
                jComboBox7.addItem(ageCategorymale);
                jComboBox8.addItem(ageCategorymale);
            }
        }
        catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }


        try {
            String query="SELECT * FROM female_age_group";
            preparedStatement=connect.prepareStatement(query);
            ResultSet rs = preparedStatement.executeQuery();
            jComboBox2.addItem("None");
            jComboBox9.addItem("None");
            jComboBox10.addItem("None");
            jComboBox11.addItem("None");
            jComboBox12.addItem("None");
            jComboBox13.addItem("None");
            for(int i = 1; rs.next(); i ++)
            {

                int id = rs.getInt("id");
                int age_group_start = rs.getInt("age_group_start");
                int age_group_end = rs.getInt("age_group_end");
                int start = age_group_start; // rs.get(row, col1) --> start of age group
                int end = age_group_end;  // rs.get(row, col2) --> end of age group

                String ageCategoryfemale = (start + " - " + end);
                String ageGroup [] = new String[] { "None" ,ageCategoryfemale };
                System.out.println( "values from female_age_group table  "+ ageCategoryfemale );
                jComboBox2.addItem(ageCategoryfemale);
                jComboBox9.addItem(ageCategoryfemale);
                jComboBox10.addItem(ageCategoryfemale);
                jComboBox11.addItem(ageCategoryfemale);
                jComboBox12.addItem(ageCategoryfemale);
                jComboBox13.addItem(ageCategoryfemale);

            }
        }
        catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        try {
            String query="SELECT * FROM kids_age_group";
            preparedStatement=connect.prepareStatement(query);
            ResultSet rs = preparedStatement.executeQuery();
            jComboBox3.addItem("None");
            jComboBox14.addItem("None");
            jComboBox15.addItem("None");
            jComboBox16.addItem("None");
            jComboBox17.addItem("None");
            jComboBox18.addItem("None");

            for(int i = 1; rs.next(); i ++)
            {

                int id = rs.getInt("id");
                int age_group_start = rs.getInt("age_group_start");
                int age_group_end = rs.getInt("age_group_end");
                int start = age_group_start; // rs.get(row, col1) --> start of age group
                int end = age_group_end;  // rs.get(row, col2) --> end of age group

                String ageCategorykids = (start + " - " + end);
                String ageGroup [] = new String[] { "None" ,ageCategorykids };
                System.out.println( "values from kids_age_group table  "+ ageCategorykids );
                jComboBox3.addItem(ageCategorykids);
                jComboBox14.addItem(ageCategorykids);
                jComboBox15.addItem(ageCategorykids);
                jComboBox16.addItem(ageCategorykids);
                jComboBox17.addItem(ageCategorykids);
                jComboBox18.addItem(ageCategorykids);

            }
        }
        catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        //        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel());
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    connect = DriverManager.getConnection(CafeBill.hmsDbUrl);
                    String query="Insert into demography(num_of_guests ,num_of_males, m_age_group_1,m_age_group_2 ,m_age_group_3, m_age_group_4, m_age_group_5,m_age_group_6, num_of_females,f_age_group_1,f_age_group_2,f_age_group_3,f_age_group_4,f_age_group_5,f_age_group_6,num_of_kids,k_age_group_1,k_age_group_2,k_age_group_3,k_age_group_4,k_age_group_5,k_age_group_6,oid,cid)"
                            + " values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                    preparedStatement=connect.prepareStatement(query);
                    preparedStatement.setInt(1, comboBox.getSelectedIndex());
                    preparedStatement.setInt(2, comboBox_1.getSelectedIndex());
                    preparedStatement.setInt(3, jComboBox1.getSelectedIndex());
                    preparedStatement.setInt(4, jComboBox4.getSelectedIndex());
                    preparedStatement.setInt(5, jComboBox5.getSelectedIndex());
                    preparedStatement.setInt(6, jComboBox6.getSelectedIndex());
                    preparedStatement.setInt(7, jComboBox7.getSelectedIndex());
                    preparedStatement.setInt(8, jComboBox8.getSelectedIndex());
                    preparedStatement.setInt(9, comboBox_2.getSelectedIndex());
                    preparedStatement.setInt(10,jComboBox2.getSelectedIndex());
                    preparedStatement.setInt(11, jComboBox9.getSelectedIndex());
                    preparedStatement.setInt(12, jComboBox10.getSelectedIndex());
                    preparedStatement.setInt(13, jComboBox11.getSelectedIndex());
                    preparedStatement.setInt(14, jComboBox12.getSelectedIndex());
                    preparedStatement.setInt(15, jComboBox13.getSelectedIndex());
                    preparedStatement.setInt(16, comboBox_3.getSelectedIndex());
                    preparedStatement.setInt(17, jComboBox3.getSelectedIndex());
                    preparedStatement.setInt(18, jComboBox14.getSelectedIndex());
                    preparedStatement.setInt(19, jComboBox15.getSelectedIndex());
                    preparedStatement.setInt(20, jComboBox16.getSelectedIndex());
                    preparedStatement.setInt(21, jComboBox17.getSelectedIndex());
                    preparedStatement.setInt(22, jComboBox18.getSelectedIndex());
                    OrderId =_cb.oid;
                    CustomerId = _cb.cid;
                    System.out.println("OrderId in Demography is: "+OrderId);
                    System.out.println("CustomerId in Demography is: "+CustomerId);
                    preparedStatement.setLong(23, OrderId );
                    preparedStatement.setLong(24, CustomerId );
                    preparedStatement.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data inserted", "MESSAGE", JOptionPane.INFORMATION_MESSAGE);
                    btnclearActionPerformed(evt);
                }
                catch (SQLException e2) {
                    // TODO Auto-generated catch block
                    e2.printStackTrace();
                }
                btnSubmitActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jLabel1.setText("Select Age Group");

        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
                comboBox.setSelectedItem("None");
                comboBox_1.setSelectedItem("None");
                jComboBox2.setSelectedItem("None");
                comboBox_3.setSelectedItem("None");
                jComboBox1.setSelectedItem("None");
                comboBox_2.setSelectedItem("None");
                jComboBox3.setSelectedItem("None");
                jComboBox4.setSelectedItem("None");
                jComboBox5.setSelectedItem("None");
                jComboBox6.setSelectedItem("None");
                jComboBox7.setSelectedItem("None");
                jComboBox8.setSelectedItem("None");
                jComboBox9.setSelectedItem("None");
                jComboBox10.setSelectedItem("None");
                jComboBox11.setSelectedItem("None");
                jComboBox12.setSelectedItem("None");
                jComboBox13.setSelectedItem("None");
                jComboBox14.setSelectedItem("None");
                jComboBox15.setSelectedItem("None");
                jComboBox16.setSelectedItem("None");
                jComboBox17.setSelectedItem("None");
                jComboBox18.setSelectedItem("None");
            }
        });

        comboBox = new JComboBox();
        comboBox.addItem("None");
        int number_to_add_max =20;
        for (int i = 1; i <= number_to_add_max; i++)
        {
            comboBox.addItem(i);
        }

        comboBox_1 = new JComboBox();
        comboBox_1.addItem("None");
        int number_to_add =10;
        for (int i = 1; i <= number_to_add; i++)
        {
            comboBox_1.addItem(i);
        }

        comboBox_2 = new JComboBox();
        comboBox_2.addItem("None");
        int number_to_add2=10;
        for (int i = 1; i <= number_to_add2; i++)
        {
            comboBox_2.addItem(i);
        }

        comboBox_3 = new JComboBox();
        comboBox_3.addItem("None");
        int number_to_add3=10;
        for (int i = 1; i <= number_to_add2; i++)
        {
            comboBox_3.addItem(i);
        }

        JLabel lblOid = new JLabel("Cid : " + CafeBill.cid);
        lblOid.hide();
        JLabel lblCid = new JLabel("Oid :"+ CafeBill.oid);
        lblCid.hide();

        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
            groupLayout.createParallelGroup(Alignment.LEADING)
                .addGroup(groupLayout.createSequentialGroup()
                    .addGap(138)
                    .addComponent(btnSubmit)
                    .addGap(18)
                    .addComponent(btnclear)
                    .addGap(18)
                    .addComponent(btnCancel))
                .addGroup(groupLayout.createSequentialGroup()
                    .addGap(31)
                    .addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                        .addGroup(groupLayout.createSequentialGroup()
                            .addComponent(lblno_of_guests)
                            .addPreferredGap(ComponentPlacement.UNRELATED)
                            .addComponent(comboBox, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE)
                            .addGap(2617)
                            .addComponent(jLabel1))
                        .addGroup(groupLayout.createSequentialGroup()
                            .addComponent(lblMale)
                            .addGap(46)
                            .addComponent(comboBox_1, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(ComponentPlacement.UNRELATED)
                            .addComponent(jComboBox4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addGap(18)
                            .addComponent(jComboBox5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addGap(4)
                            .addComponent(jComboBox6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addGap(18)
                            .addComponent(jComboBox7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
                .addGroup(groupLayout.createSequentialGroup()
                    .addGap(31)
                    .addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                        .addGroup(groupLayout.createSequentialGroup()
                            .addComponent(lblOid)
                            .addGap(18)
                            .addComponent(lblCid))
                        .addGroup(groupLayout.createSequentialGroup()
                            .addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                                .addComponent(lblFemale)
                                .addComponent(lblKids))
                            .addGap(18)
                            .addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                                .addGroup(groupLayout.createSequentialGroup()
                                    .addComponent(comboBox_3, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                                    .addGap(18)
                                    .addComponent(jComboBox3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addGap(18)
                                    .addComponent(jComboBox14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBox15, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBox16, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addGap(18)
                                    .addComponent(jComboBox17, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addGap(18)
                                    .addComponent(jComboBox18, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGroup(groupLayout.createSequentialGroup()
                                    .addComponent(comboBox_2, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                                    .addGap(18)
                                    .addComponent(jComboBox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addGap(18)
                                    .addComponent(jComboBox9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addGap(18)
                                    .addComponent(jComboBox10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(ComponentPlacement.RELATED)
                                    .addComponent(jComboBox11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(ComponentPlacement.RELATED)
                                    .addComponent(jComboBox12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBox13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))))
                    .addGap(2353))
        );
        groupLayout.setVerticalGroup(
            groupLayout.createParallelGroup(Alignment.LEADING)
                .addGroup(groupLayout.createSequentialGroup()
                    .addGap(34)
                    .addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblno_of_guests)
                        .addComponent(comboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGap(21)
                    .addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                        .addGroup(groupLayout.createSequentialGroup()
                            .addGap(3)
                            .addComponent(lblMale))
                        .addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
                            .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBox_1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
                            .addComponent(jComboBox5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addComponent(jComboBox7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGap(37)
                    .addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                        .addGroup(groupLayout.createSequentialGroup()
                            .addGap(3)
                            .addComponent(lblFemale))
                        .addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
                            .addComponent(jComboBox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBox_2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                    .addGap(40)
                    .addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                        .addGroup(groupLayout.createSequentialGroup()
                            .addGap(3)
                            .addComponent(lblKids))
                        .addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
                            .addComponent(jComboBox3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox15, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox16, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox17, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox18, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBox_3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                    .addGap(25)
                    .addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(lblOid)
                        .addComponent(lblCid))
                    .addGap(21)
                    .addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(btnSubmit)
                        .addComponent(btnclear)
                        .addComponent(btnCancel))
                    .addGap(46))
        );
        getContentPane().setLayout(groupLayout);
        getContentPane().setPreferredSize(new Dimension(900, 600));
        pack();
    }// </editor-fold>
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        //        System.exit(0);
        setVisible (false);
    }

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        comboBox.setSelectedItem("None");
        comboBox_1.setSelectedItem("None");
        comboBox_3.setSelectedItem("None");
        jComboBox1.setSelectedItem("None");
        comboBox_2.setSelectedItem("None");
        jComboBox3.setSelectedItem("None");
        jComboBox4.setSelectedItem("None");
        jComboBox5.setSelectedItem("None");
        jComboBox6.setSelectedItem("None");
        jComboBox7.setSelectedItem("None");
        jComboBox8.setSelectedItem("None");
        jComboBox9.setSelectedItem("None");
        jComboBox10.setSelectedItem("None");
        jComboBox11.setSelectedItem("None");
        jComboBox12.setSelectedItem("None");
        jComboBox13.setSelectedItem("None");
        jComboBox14.setSelectedItem("None");
        jComboBox15.setSelectedItem("None");
        jComboBox16.setSelectedItem("None");
        jComboBox17.setSelectedItem("None");
        jComboBox18.setSelectedItem("None");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Demography.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Demography.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Demography.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Demography.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Demography().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnclear;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox13;
    private javax.swing.JComboBox jComboBox14;
    private javax.swing.JComboBox jComboBox15;
    private javax.swing.JComboBox jComboBox16;
    private javax.swing.JComboBox jComboBox17;
    private javax.swing.JComboBox jComboBox18;

    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFemale;
    private javax.swing.JLabel lblKids;
    private javax.swing.JLabel lblMale;
    private javax.swing.JLabel lblno_of_guests;
    private JComboBox comboBox;
    private JComboBox comboBox_1;
    private JComboBox comboBox_2;
    private JComboBox comboBox_3;
    private long OrderId;
    private long CustomerId;
}