CREATE TABLE timeSheet(
timeSheetId INT(11) PRIMARY KEY AUTO_INCREMENT,
empId INT(11),
currDate DATETIME DEFAULT NULL,
startTime DATETIME DEFAULT NULL,
pauseTime DATETIME DEFAULT NULL,
resumeTime DATETIME DEFAULT NULL,
stopTime DATETIME DEFAULT NULL,
totalTime TIME DEFAULT NULL,
FOREIGN KEY(empId) REFERENCES emp(empid),
CONSTRAINT `Unique` Unique KEY (empId,currDate));