CREATE TABLE timeSheet(
timeSheetId INT(11) PRIMARY KEY AUTO_INCREMENT,
empId INT(11) UNIQUE,
currDate DATE DEFAULT NULL,
startTime TIME DEFAULT NULL,
pauseTime TIME DEFAULT NULL,
resumeTime TIME DEFAULT NULL,
stopTime TIME DEFAULT NULL,
totalTime TIME DEFAULT NULL,
FOREIGN KEY(empId) REFERENCES emp(empid));	